### ISSUE TITLE
Benoem de naam van de link inplaats van # te gebruiken

### ISSUE THREAD

**Issue by Metehan2003** [rileyesther/the-startup-responsive-interactieve-website#1]
https://github.com/rileyesther/the-startup-responsive-interactieve-website/blob/80b476669487eccef33153be2c9c963dcceb11f2/index.html#L13-L17

Je hebt in je html # gebruikt om links te laten zien. Om je code duidelijker te maken kan je het best de namen gebruiken van de links.

**Comment by rileyesther** [comment]
zal ik de volgende keer doen !
