### ISSUE TITLE
Dropdown filter kon je niet bewegen

### ISSUE THREAD

**Issue by Naddybs** [rileyesther/the-startup-responsive-interactieve-website#3]
https://github.com/rileyesther/the-startup-responsive-interactieve-website/blob/89a2fea499e9429d0aad41d8ac5d3bb31306569e/index.html#L37-L44

Dit stond in de header, vandaar dat je hem niet naar beneden kreeg.

**Comment by rileyesther** [comment]
ik heb hem verplaatst , dank je wel!
