### ISSUE TITLE
Div's lijken niet goed gesloten te zijn

### ISSUE THREAD

**Issue by zainablfz** [rileyesther/the-startup-responsive-interactieve-website#4]
https://github.com/rileyesther/the-startup-responsive-interactieve-website/blob/89a2fea499e9429d0aad41d8ac5d3bb31306569e/index.html#L12-L21

https://github.com/rileyesther/the-startup-responsive-interactieve-website/blob/89a2fea499e9429d0aad41d8ac5d3bb31306569e/index.html#L37-L44

Hier sluit je 2x een `<div>` element, maar er wordt alleen 1x geopend. Verder in de code heb je dan dat er nog een sluiting van de `<div>` element mist.

De overbodige kan je verwijderen en bij de dropdown toevoegen.

**Comment by rileyesther** [comment]
gefixt , dank je wel, ik ben langs al mijn divs gegaan en heb nu het juiste aantal geopende en gesloten divs
